# Dockerc compose only for developing purpose

version: '3.8'

services:
  couchdb:
    build:
      context: ./couchdb
      dockerfile: Dockerfile
    container_name: hr_couchdb
    ports:
      - '5984:5984'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin

  dbinit:
    image: curlimages/curl
    container_name: hr_couchdb_init
    depends_on:
      - couchdb
    command: >
      sh -c
      "sleep 5s &&
      curl -X PUT http://admin:admin@localhost:5984/_global_changes &&
      curl -X PUT http://admin:admin@localhost:5984/_users/_security -d '{\"members\": {}, \"admins\": {\"roles\":['worker'] [\"_admin\"] }}' &&
      curl -X PUT http://admin:admin@localhost:5984/taskbox?partitioned=false &&
      curl -X PUT http://admin:admin@localhost:5984/taskbox/_security -d '{\"members\": {}, \"admins\": {\"roles\":['worker'] [\"_admin\"] }}'
